name: Build APK

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleTabrizRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-tabriz-release
        path: app/build/outputs/apk/tabriz/release/app-tabriz-release.apk
